theme: jekyll-theme-cayman
title: Computer-Designed Organisms
description: A scalable pipeline for creating functional novel lifeforms (or, Xenobots).
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
