theme: jekyll-theme-cayman
title: Computer-designed organisms
description: A scalable pipeline for creating novel organisms, such as xenobots.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
